#%RAML 1.0 Trait
responses:
      200:
        body:
          application/json: 
            example:
              {"message": " successful."}
      400:
        description: Bad Request
      500:
        description: Internal server error
	

    